GET {{url}}/api/transactions
Authorization: Bearer {{token}}

###


GET {{url}}/api/summary/2023-01/2023-12
Accept: application/json
Authorization: Bearer {{token}}

###

GET {{url}}/api/categories
Accept: application/json
Authorization: Bearer {{token}}

###

GET {{url}}/api/import/accounts
Accept: application/json
Authorization: Bearer {{token}}
